project:
  type: website

website:
  description: "A blog built with Quarto"
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        text: Github
        href: https://github.com/
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/marios-lazaros-michailidis/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

execute:
  freeze: auto

